import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/Footer";
import { Navbar } from "@/app/components/Navbar"
import { SmoothScroll } from "./smooth-scroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Lattiz",
  description: "",
  keywords: ["nextjs", "react", "typescript", "tailwindcss"],
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://nextjs.org",
    siteName: "Create Next App",
    images: [
      {
        url: "https://nextjs.org/og.png",
        width: 800,
        height: 600,
      },
      {
        url: "https://nextjs.org/og-alt.png",
        width: 1800,
        height: 1600,
        alt: "My custom alt",
      },
    ],
    locale: "es_ES",
    type: "website",
  }
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="es"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full bg-background antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll>
          <Navbar />
          {children}
          <div
            aria-hidden="true"
            className="fixed bottom-0 left-0 right-0 z-50 h-14 pointer-events-none"
            style={{
              backdropFilter: "blur(1px)",
              background:
                "linear-gradient(to top, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.1) 70%, transparent 100%)",
            }}
          />
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}